version: "2"

services:
  api:
    image: ghcr.io/saleor/saleor:unstable-main
    ports:
      - 8000:8000
    networks:
      - saleor-platform
    depends_on:
      - db
      - redis
    volumes:
      # shared volume between worker and api for media
      - saleor-media:/app/media
    command: python manage.py runserver 0.0.0.0:8000
    env_file: common.env
    environment:
      - STOREFRONT_URL=http://localhost:3000/
      - DASHBOARD_URL=http://localhost:9000/

  dashboard:
    image: ghcr.io/artursmet/saleor-dashboard:dev
    ports:
      - 9000:80

  db:
    image: library/postgres:11.1-alpine
    networks:
      - saleor-platform
    volumes:
      - saleor-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=saleor
      - POSTGRES_PASSWORD=saleor

  redis:
    image: library/redis:5.0-alpine
    networks:
      - saleor-platform
    volumes:
      - saleor-redis:/data

  worker:
    image: ghcr.io/saleor/saleor:unstable-main
    command: celery -A saleor --app=saleor.celeryconf:app worker --loglevel=info -B
    networks:
      - saleor-platform
    env_file: common.env
    depends_on:
      - redis
      - mailhog
    volumes:
      # shared volume between worker and api for media
      - saleor-media:/app/media

  mailhog:
    image: mailhog/mailhog
    ports:
      - 1025:1025 # smtp server
      - 8025:8025 # web ui. Visit http://localhost:8025/ to check emails
    networks:
      - saleor-platform
  
volumes:
  saleor-db:
    driver: local
  saleor-redis:
    driver: local
  saleor-media:

networks:
  saleor-platform:
    driver: bridge
